// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add from "./routes/add.tsx";
import * as $api_ByName_name_ from "./routes/api/ByName/[name].ts";
import * as $api_addPokemon from "./routes/api/addPokemon.ts";
import * as $api_getAllPokemon from "./routes/api/getAllPokemon.ts";
import * as $index from "./routes/index.tsx";
import * as $pokemon_name_ from "./routes/pokemon/[name].tsx";
import * as $search from "./routes/search.tsx";
import * as $PokemonCreate from "./islands/PokemonCreate.tsx";
import * as $PokemonItem from "./islands/PokemonItem.tsx";
import * as $PokemonSearch from "./islands/PokemonSearch.tsx";
import * as $PokemonesList from "./islands/PokemonesList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add.tsx": $add,
    "./routes/api/ByName/[name].ts": $api_ByName_name_,
    "./routes/api/addPokemon.ts": $api_addPokemon,
    "./routes/api/getAllPokemon.ts": $api_getAllPokemon,
    "./routes/index.tsx": $index,
    "./routes/pokemon/[name].tsx": $pokemon_name_,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/PokemonCreate.tsx": $PokemonCreate,
    "./islands/PokemonItem.tsx": $PokemonItem,
    "./islands/PokemonSearch.tsx": $PokemonSearch,
    "./islands/PokemonesList.tsx": $PokemonesList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
